# Generated by Django 3.2.12 on 2023-04-20 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportGourp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('admin', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupportGourpUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suuport_gourp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.supportgourp')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('requirements', models.TextField()),
                ('notes', models.TextField()),
                ('help_contacts', models.TextField()),
                ('suuport_gourp', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.supportgourp')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resedence', models.CharField(max_length=100)),
                ('step_status', models.IntegerField()),
                ('step_note', models.TextField()),
                ('steps_log', models.JSONField()),
                ('cv', models.URLField()),
                ('phone_numer', models.CharField(max_length=100)),
                ('study_log', models.JSONField()),
                ('followed_scholarships', models.JSONField()),
                ('earned_scholarships', models.JSONField()),
                ('current_step', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.studentstep')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
