# Generated by Django 3.2.12 on 2023-04-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cvx_acceptance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentstep',
            name='id_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='step_status',
            field=models.IntegerField(default=1),
        ),
    ]
