# Generated by Django 3.2.12 on 2023-04-23 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20230423_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.studentstep'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cv',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='earned_scholarships',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='profile',
            name='followed_scholarships',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_numer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='step_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='steps_log',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='profile',
            name='study_log',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='studentstep',
            name='suuport_gourp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.supportgourp'),
        ),
        migrations.AlterField(
            model_name='supportgourp',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supportgourpuser',
            name='suuport_gourp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.supportgourp'),
        ),
        migrations.AlterField(
            model_name='supportgourpuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
