# Generated by Django 3.2.12 on 2023-04-23 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_supportgrouphelprequest_supportgroupjoinrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentstep',
            old_name='suuport_gourp',
            new_name='support_gourp',
        ),
        migrations.RenameField(
            model_name='supportgourpuser',
            old_name='suuport_gourp',
            new_name='support_gourp',
        ),
        migrations.RenameField(
            model_name='supportgrouphelprequest',
            old_name='suuport_gourp',
            new_name='support_gourp',
        ),
        migrations.RenameField(
            model_name='supportgroupjoinrequest',
            old_name='suuport_gourp',
            new_name='support_gourp',
        ),
    ]
