# Generated by Django 3.2.12 on 2023-04-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_branch_of_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='branch_of_interest_degree_type',
            field=models.CharField(blank=True, choices=[(1, 'Bachelor'), (2, 'Master'), (3, 'PHD')], max_length=100),
        ),
    ]
