# Generated by Django 3.2.12 on 2023-04-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20230424_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='administration_profile',
            name='cvx_acceptance_handler',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='branch_of_interest_degree_type',
            field=models.CharField(blank=True, choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PHD', 'PHD')], max_length=100),
        ),
    ]
