# Generated by Django 3.2.12 on 2023-04-28 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_procedurestep_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='current_step',
        ),
        migrations.AddField(
            model_name='profile',
            name='current_procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.procedure'),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_procedure_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.procedurestep'),
        ),
    ]
