# Generated by Django 3.2.12 on 2023-04-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_administration_profile_change_current_procedures'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_procedure_completed',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
