# Generated by Django 3.2.12 on 2023-04-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profile_current_procedure_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='administration_profile',
            name='add_university',
            field=models.BooleanField(default=1),
        ),
    ]
