# Generated by Django 3.2.12 on 2023-05-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_administration_profile_add_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_procedure_completed',
            field=models.BooleanField(default=0),
        ),
    ]
