# Generated by Django 3.2.12 on 2023-05-02 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0016_alter_profile_current_procedure_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportgrouphelprequest',
            name='helper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='helper', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supportgrouphelprequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
