# Generated by Django 3.2.12 on 2023-05-02 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20230502_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='step_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentstep',
            name='support_gourp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.supportgourp'),
        ),
    ]
