# Generated by Django 3.2.12 on 2023-05-02 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20230502_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedure',
            old_name='step_note',
            new_name='about',
        ),
    ]
