# Generated by Django 3.2.12 on 2023-04-28 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=100)),
                ('support_contacts', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('apply_link', models.URLField()),
                ('scholarship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='universities.scholarship')),
            ],
        ),
        migrations.AddField(
            model_name='scholarship',
            name='university',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='universities.university'),
        ),
    ]
