# Generated by Django 3.2.12 on 2023-04-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_university_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='programmes_page',
            field=models.URLField(default='https://www.youtube.com/'),
        ),
    ]
