# Generated by Django 3.2.12 on 2023-05-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_auto_20230428_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarshipsession',
            name='about',
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='about',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='support_contacts',
            field=models.TextField(),
        ),
    ]
